<?php /* Smarty version 2.6.21, created on 2012-01-03 05:18:34
         compiled from download.tpl */ ?>
<!--This section is generated by smarty template-->
<!-- Start Top -->
 		<div class="master">					
			<div class="text_chapter">
				フリー素材一覧
			</div>
			<div class="text_default">
				左のメニューからカテゴリを選んでください。
			</div>
			<div id="MENU_SIDE">
				カテゴリ
			</div>
			<div id="CONTENTS">
				プレビュー画像
			</div>
			<hr class="line" />
		</div>
<!-- End Top -->
