<?php /* Smarty version 2.6.21, created on 2012-01-03 05:21:29
         compiled from disclaimer.tpl */ ?>
<!--This section is generated by smarty template-->
<!-- Start Top -->
 		<div class="master">					
			<div class="text_chapter">
				免責事項
			</div>
			<div class="text_default">
				ファイルの取り扱い等は全て自己責任の下で行ってください。<br />
				（万一何らかの損害が発生した場合、責任は全て使用者が負うものとします。）<br />
				<br />
				コンテスト等の応募作品に使用する場合、<br />
				添付書類などコンテスト開催者に見える場所に出典を必ず明記して下さい。<br />
				コンテスト開催者等との著作権についてのトラブルを防止するためです。<br />
				<br />
				トラフィック対策のため、直リンク対策をしています。<br />
				画像をリンクして使用した場合、<br />
				一定期間後に表示されなくなったりすることがあります。<br />
			</div>
			<hr class="line" />
		</div>
<!-- End Top -->
