<?php /* Smarty version 2.6.21, created on 2012-01-03 05:12:10
         compiled from legal.tpl */ ?>
<!--This section is generated by smarty template-->
<!-- Start Top -->
 		<div class="master">					
			<div class="text_chapter">
				利用規約
			</div>
			<div class="text_default">
				安心して当サイトの素材をご利用して頂けるように、<br />
				いくつかの利用規約を設けております。<br />
				<br />
				素材をご利用の際は下記の内容を必ずご確認下さい。<br />
				よろしくお願いいたします。<br />
				<br />
			</div>
			<div class="text_section">
				使用範囲について
			</div>
			<table class="table_standard">
				<tr>
					<td rowspan="2">作品内での用途/目的</td>
					<td colspan="6">作品種別ごとの使用可否</td>
				</tr>
				<tr>
					<td>静止画</td>
					<td>動画</td>
					<td>アプリケーション</td>
					<td>WEBサイト</td>
					<td>出版物</td>
					<td>その他</td>
				</tr>
				<tr>
					<td>営利活動/商業利用</td>
					<td>使用可能</td>
					<td>使用可能</td>
					<td>使用可能</td>
					<td>使用可能</td>
					<td>使用可能</td>
					<td>使用可能</td>
				</tr>
				<tr>
					<td>１８禁作品等での使用</td>
					<td>使用可能</td>
					<td>使用可能</td>
					<td>使用可能</td>
					<td>使用可能</td>
					<td>使用可能</td>
					<td>使用可能</td>
				</tr>
			</table>
			<br />
			<div class="text_section">
				素材の加工などについて
			</div>
			<table class="table_standard">
				<tr>
					<td rowspan="2">加工内容</td>
					<td colspan="6">作品種別ごとの使用可否</td>
				</tr>
				<tr>
					<td>静止画</td>
					<td>動画</td>
					<td>アプリケーション</td>
					<td>WEBサイト</td>
					<td>出版物</td>
				</tr>
				<tr>
					<td>画像加工</td>
					<td>可能</td>
					<td>可能</td>
					<td>可能</td>
					<td>可能</td>
					<td>可能</td>
				</tr>
				<tr>
					<td>ファイル名変更</td>
					<td>可能</td>
					<td>可能</td>
					<td>可能</td>
					<td>可能</td>
					<td>可能</td>
				</tr>
				<tr>
					<td>ファイル形式変更</td>
					<td>可能</td>
					<td>可能</td>
					<td>可能</td>
					<td>可能</td>
					<td>可能</td>
				</tr>
			</table>
			<br />
			<div class="text_section">
				使用時の連絡や著作権表記など
			</div>
				<table class="table_standard">
				<tr>
					<td rowspan="2">使用条件など</td>
					<td colspan="6">作品種別ごとの使用可否</td>
				</tr>
				<tr>
					<td>静止画</td>
					<td>動画</td>
					<td>アプリケーション</td>
					<td>WEBサイト</td>
					<td>出版物</td>
				</tr>
				<tr>
					<td>使用時の連絡</td>
					<td>不要</td>
					<td>不要</td>
					<td>不要</td>
					<td>不要</td>
					<td>不要</td>
				</tr>
				<tr>
					<td>作品内への著作権表記</td>
					<td>不要</td>
					<td>不要</td>
					<td>不要</td>
					<td>不要</td>
					<td>不要</td>
				</tr>
				<tr>
					<td>使用時にWEBサイトを<br />作品内等でリンク</td>
					<td>不要</td>
					<td>不要</td>
					<td>不要</td>
					<td>不要</td>
					<td>不要</td>
				</tr>
			</table>
			<br />
			<div class="text_section">
				禁止事項/その他の注意事項
			</div>
			<div class="text_default">
				※当サイト内の「フリー素材」とは、利用規約の範囲内であればフリー素材として用意している各画像データ等になります。このフリー素材を利用規約の範囲内において、無償で自由に使用いただけます。ただし、著作権の放棄はしていません。<br />
　				<br />
				※何らかの創作物の一部として使用せずに、フリー素材その物のみを無断で転載・配布する事は禁止いたします。<br />
				<br />
				※当サイトのフリー素材を加工・改造した物を素材として配布する事も禁止いたします。<br />
　				<br />
				※もし、素材データとしての収録・転載・再配布を行いたい場合は 事前にご相談下さい。<br />
　				<br />
				※素材ファイルへの直リンクはご遠慮ください。<br />
				<br />
				※<a href="./index.php?a=disclaimer">免責事項</a>があります。
			</div>			
			<hr class="line" />
		</div>
<!-- End Top -->
