<?php /* Smarty version 2.6.21, created on 2011-12-31 23:30:23
         compiled from top.tpl */ ?>
<!--This section is generated by smarty template-->
<!-- Start Top -->
 		<div class="master">					
			<div class="text_chapter">
				ポコポヨドットコムって？
			</div>
			<div class="text_default">
				フリー素材用のイラストを中心に置いているWEBサイトです。
			</div>
			<hr class="line" />
		</div>
<!-- End Top -->
