<!--This section is generated by smarty template-->
<!-- Start Top -->
<!-- EVE BROWSER対応に改装する場合、UTF-8のXML1.1にすること -->
		<div class="INDEX">
			<img src="./img/jads.gif" width="60" height="60" alt="JADSのロゴマーク" class="CORPLOGO" />
			JAPANESE MUTUAL AID DELEGATION TO DEEP SPACE
		</div>
 
 		<div class="MASTER">
			<hr class="LINE" />
			
			<div class="CAPTION1">
				変数：XML_APIの内容
			</div>
			<div class="TEXT">
				{$xml}
			</div>
			
			<hr class="LINE" />
		</div>
<!-- End Top -->

