<!--This section is generated by smarty template-->
<!-- Start Top -->
 		<div class="master">					
			<div class="text_chapter">
				ポコポヨドットコムって？
			</div>
			<div class="text_default">
				フリー素材用のイラストを中心に置いているWEBサイトです。
			</div>
			<hr class="line" />
		</div>
<!-- End Top -->

